name: Update MM2 Prices

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install playwright
      - run: playwright install chromium
      - run: python updater.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add prices.json
          git commit -m "auto update" || echo "No changes"
          git push
